In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
array.shape

(3, 3)

In [4]:
array.ndim

2

In [5]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array[:2,1:]

array([[2, 3],
       [5, 6]])

In [7]:
#Atribuindo um valor
array[1,1] = 100

In [8]:
array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [9]:
#Retorna terceira linha da matriz
array[2,]

array([7, 8, 9])

In [10]:
#Transpose
array.T

array([[  1,   4,   7],
       [  2, 100,   8],
       [  3,   6,   9]])

In [11]:
array5 = np.arange(50)*2

In [12]:
array5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [13]:
array5[5:10:2]

array([10, 14, 18])

In [14]:
array6 = array5.copy()

In [15]:
array6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [16]:
array6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [17]:
array6[0] = 100

In [18]:
array6

array([100,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98])

In [19]:
array5[1:5] = 100

In [20]:
array5

array([  0, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98])

In [21]:
#Transformando Matrizes em Arrays
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array2.ravel()

In [22]:
#Verifica se existe algum elemento igual a condição
print(np.any((array2 % 2)==0))
print(np.any(array2 <5))

True

In [23]:
#Verifica se todos os elementos da matriz são iguais a condição
print(np.all(array2 <5))
print(np.all(array2 <15))

False

In [26]:
#Adicionando dimensão
array6 = np.array([14,15,16])
array6[:,np.newaxis]

array([[14],
       [15],
       [16]])

In [27]:
array6 = array6[:,np.newaxis]

In [ ]:
#Ordenando array
array6 = np.array([14,15,16])
array6.sort()


In [35]:
matriz1 = np.array([[14,22,313],[722,52,4111],[7132,821,11129]])




In [36]:
#ordena por linha
matriz1.sort(axis=1)
matriz1

array([[   14,    22,   313],
       [   52,   722,  4111],
       [  821,  7132, 11129]])

In [39]:
#ordena coluna
matriz1 = np.array([[14,22,31300],[722,52,4111],[7132,821,11129]])
matriz1.sort(axis=0)
matriz1

array([[   14,    22,  4111],
       [  722,    52, 11129],
       [ 7132,   821, 31300]])

In [41]:
import pandas as pd
from sklearn.datasets import load_iris


In [42]:
iris = load_iris()

In [51]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [52]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [58]:
df.get('sepal length (cm)')

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64

In [63]:
df.iloc[0]

sepal length (cm)    5.1
sepal width (cm)     3.5
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0, dtype: float64

In [64]:
df.loc[0]

sepal length (cm)    5.1
sepal width (cm)     3.5
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0, dtype: float64

In [68]:
#Retorna todas as colunas
df.iloc[2:4,:]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [67]:
#Retorna somente a coluna
df.iloc[2:4,2]


2    1.3
3    1.5
Name: petal length (cm), dtype: float64

In [69]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [77]:
from sklearn.datasets import load_boston

In [78]:
boston = load_boston()

E:\CASSIO\04 - CURSOS\DSA\venv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing data

In [80]:
df = pd.DataFrame(boston.data, columns=boston.feature_names)

In [81]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [82]:
df.count()

CRIM       506
ZN         506
INDUS      506
CHAS       506
NOX        506
RM         506
AGE        506
DIS        506
RAD        506
TAX        506
PTRATIO    506
B          506
LSTAT      506
dtype: int64

In [83]:
del df['CRIM']

In [86]:
df.groupby('RAD').groups

{1.0: [0, 193, 194, 254, 255, 283, 284, 285, 286, 331, 332, 341, 342, 349, 350, 501, 502, 503, 504, 505], 2.0: [1, 2, 56, 88, 89, 90, 91, 95, 96, 97, 98, 99, 120, 121, 122, 123, 124, 125, 126, 196, 197, 198, 201, 202], 3.0: [3, 4, 5, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 54, 64, 84, 85, 86, 87, 179, 180, 181, 182, 183, 184, 185, 186, 199, 200, 256, 269, 270, 271, 272, 273, 345, 346], 4.0: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 50, 51, 52, 53, 65, 66, 67, 68, 69, 70, 71, 72, 73, 80, 81, 82, 83, 92, 93, 94, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 195, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 274, 275, 276, 277, 278, 290, 291, 292, 293, 294, 295, 296, 297, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 328, 329, 330, 347, ...], 5.0: [6, 7, 8, 9, 10, 11, 12, 35, 36, 37, 38, 55, 57, 74, 75, 76, 77, 78, 79, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 142,