#### Map

In [2]:
import numpy as np

In [1]:
def sqrt(x):
    return x**0.5


In [3]:
array = np.array([1,4,9,16,25])

In [6]:
list_map_result = map(sqrt,array)

In [9]:
print(list(list_map_result))

[1.0, 2.0, 3.0, 4.0, 5.0]


#### Filter

In [10]:
def is_even(x):
    return x%2==0

In [11]:
array = np.array([1,4,9,16,25])

In [12]:
list_filter_result = filter(is_even,array)

In [13]:
print(list(list_filter_result))

[4, 16]


#### Reduce

In [14]:
from functools import reduce

In [15]:
def add(x,y):
    return x+y

In [16]:
array = np.array([1,4,9,16,25])

In [17]:
reduce_result = reduce(add,array)

In [18]:
reduce_result

55

#### List Comprehension

In [22]:
[item**2 for item in array]


[1, 16, 81, 256, 625]

In [23]:
[item for item in array if item%2==0]

[4, 16]

#### Functions Lambda

In [24]:
list(map(lambda x:x**2,array))

[1, 16, 81, 256, 625]

In [26]:
#Help
?array

In [28]:
%timeit list(map(lambda x:x**2,array))

2.66 µs ± 430 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### Concatenate and Join: Numpy

In [29]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

print(np.concatenate([array1,array2]))

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
a = np.ones((3,3))
b = np.zeros((3,3))


In [33]:
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [35]:
#Joining arrays
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.array([11,12,13,14,15])

In [36]:
np.column_stack((a,b,c))

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [37]:
np.row_stack((a,b,c))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
#Split arrays
a = np.array([1,2,3,4,5,6,7,8,9,10])
c, d = np.split(a,[3])

In [39]:
c

array([1, 2, 3])

In [40]:
d

array([ 4,  5,  6,  7,  8,  9, 10])

#### Persistent Arrays

In [41]:
np.save('array1',array1)

In [42]:
loaded = np.load('array1.npy')

In [43]:
loaded

array([1, 2, 3, 4, 5])